import CoreModel
import Foundation

/// Getting everything back out.
///
/// The project's stated position is that it should not own your data, and until now that was
/// a sentence in a README with no code behind it. This is the code.
///
/// Two formats, because they answer different questions. **JSONL** is one file per table,
/// newline-delimited, streamable, and losslessly re-importable: it is the archival copy.
/// **Markdown** is the readable copy, for when you want to know what the thing believes
/// without writing a parser.
///
/// Neither includes credentials, because none are stored. `source.config` records environment
/// variable names only, and it is exported as-is.
public struct Exporter: Sendable {
    private let store: Store

    public init(store: Store) {
        self.store = store
    }

    public enum Format: String, Sendable, CaseIterable {
        case jsonl
        case markdown

        public var label: String {
            switch self {
            case .jsonl: "JSONL (archival, re-importable)"
            case .markdown: "Markdown (readable)"
            }
        }
    }

    public struct Outcome: Sendable {
        public var directory: URL
        public var files: [(name: String, rows: Int, bytes: Int)]
        public var totalBytes: Int { files.reduce(0) { $0 + $1.bytes } }
    }

    /// Every table that carries user-derived content, in dependency order.
    ///
    /// `schema_migration` is deliberately included: without knowing which migrations an export
    /// was taken under, a future reader cannot tell what the columns mean.
    static let tables = [
        "source", "object", "chunk", "evidence", "entity", "entity_alias", "edge",
        "claim", "claim_evidence", "contradiction", "belief", "correction", "event",
        "receipt", "receipt_evidence", "receipt_claim", "embedding_run", "schema_migration",
    ]

    public func export(to directory: URL, format: Format, log: @Sendable (String) -> Void = { _ in }) async throws -> Outcome {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)

        switch format {
        case .jsonl: return try await exportJSONL(to: directory, log: log)
        case .markdown: return try await exportMarkdown(to: directory, log: log)
        }
    }

    // MARK: - JSONL

    private func exportJSONL(to directory: URL, log: @Sendable (String) -> Void) async throws -> Outcome {
        var files: [(String, Int, Int)] = []

        for table in Self.tables {
            // `chunk_vector` is excluded from the row loop and handled separately: hundreds of
            // megabytes of base64 floats would dominate the export, and they are recomputable
            // from chunk text by re-running `embed`. Archival copies should not carry a
            // derived artifact that large.
            let rows = try await store.database.query("SELECT * FROM \(table)")
            var text = ""
            for row in rows {
                guard let line = row.jsonLine() else { continue }
                text += line + "\n"
            }

            let url = directory.appendingPathComponent("\(table).jsonl")
            try text.write(to: url, atomically: true, encoding: .utf8)
            files.append((url.lastPathComponent, rows.count, text.utf8.count))
            log("\(table): \(rows.count) rows")
        }

        let vectors = try await store.database.scalarInt("SELECT COUNT(*) FROM chunk_vector")
        let readme = """
        # OpenCore export

        Taken \(ISO8601DateFormatter().string(from: Date())).

        One file per table, newline-delimited JSON, one object per line. Column names match the
        schema in `Sources/CoreStore/Resources/*.sql`; `schema_migration.jsonl` records which
        migrations this export was taken under, which is what tells a future reader what the
        columns mean.

        ## What is not here

        `chunk_vector` (\(vectors) rows) is omitted. Embeddings are derived from chunk text and
        are recomputable with `opencore embed`; including them would add hundreds of megabytes
        of base64 floats that describe nothing the text does not already say.

        Nothing else is omitted. There are no credentials in this export because there are none
        in the database: `source.config` records the *names* of environment variables, never
        their values.

        ## Rebuilding from this

        `object.jsonl` is the floor. Everything else in here is derived from it and can be
        regenerated by re-importing objects and running `opencore rebuild`. If the two ever
        disagree, the objects are right.
        """
        let readmeURL = directory.appendingPathComponent("README.md")
        try readme.write(to: readmeURL, atomically: true, encoding: .utf8)
        files.append((readmeURL.lastPathComponent, 0, readme.utf8.count))

        return Outcome(directory: directory, files: files)
    }

    // MARK: - Markdown

    private func exportMarkdown(to directory: URL, log: @Sendable (String) -> Void) async throws -> Outcome {
        var text = "# OpenCore\n\nExported \(ISO8601DateFormatter().string(from: Date())).\n\n"

        let sources = try await store.sources()
        text += "## Sources\n\n"
        for source in sources {
            let synced = source.lastSyncedAt.map { ISO8601DateFormatter().string(from: $0) } ?? "never"
            text += "- **\(source.displayName)** (\(source.kind.rawValue)) · last synced \(synced)\n"
        }

        text += "\n## What it currently believes\n\n"
        text += "Marked `observed` when read straight from source data, `inferred` when concluded.\n\n"

        var claimCount = 0
        for entity in try await store.entities() {
            let claims = try await store.claims(subject: entity.id)
            guard !claims.isEmpty else { continue }
            text += "### \(entity.canonicalName)\n\n"
            for claim in claims {
                let value: String = if let object = claim.objectEntity {
                    try await store.entity(object)?.canonicalName ?? "?"
                } else {
                    claim.literal ?? "?"
                }
                let from = claim.validity.validFrom.map { " (from \(ISO8601DateFormatter().string(from: $0).prefix(10)))" } ?? ""
                text += "- `\(claim.derivation.rawValue)` \(claim.predicate.replacingOccurrences(of: "_", with: " ")) → **\(value)**"
                text += " · confidence \(String(format: "%.2f", claim.confidence)) · \(claim.authority.label)\(from)\n"
                claimCount += 1
            }
            text += "\n"
        }

        let contradictions = try await store.contradictions()
        if !contradictions.isEmpty {
            text += "## Contradictions\n\n"
            for item in contradictions {
                text += "- \(item.kind.rawValue) → **\(item.resolution.rawValue)**: \(item.reason)\n"
            }
            text += "\n"
        }

        text += """
        ## Note on what this file is

        This is the readable copy, and it is lossy: it shows current beliefs, not the evidence
        under them, not superseded claims, and not the receipts. For the complete, re-importable
        copy, export as JSONL instead.
        """

        let url = directory.appendingPathComponent("opencore.md")
        try text.write(to: url, atomically: true, encoding: .utf8)
        log("wrote \(claimCount) claims across \(try await store.entities().count) entities")

        return Outcome(directory: directory, files: [(url.lastPathComponent, claimCount, text.utf8.count)])
    }
}

extension Row {
    /// Render a row as one JSON object. `nil` if it cannot be encoded, which should not happen
    /// for any column type the schema uses.
    func jsonLine() -> String? {
        guard let data = try? JSONSerialization.data(withJSONObject: jsonObject(), options: [.sortedKeys]) else {
            return nil
        }
        return String(data: data, encoding: .utf8)
    }
}
